### ISSUE TITLE
Nice! What is your usage (just curious :))?

### ISSUE THREAD

**Issue by FGRibreau** [digmore/redis-to-pushed#1]
Nice work @digmore, but what is your usage (just curious :))?

Either way, redis-to-pushed will be shared in our next [RedisWeekly](http://redisweekly.com) tomorrow morning!

**Comment by digmore** [comment]
Thanks for the comment @FGRibreau  :-)

I am planning to add Pushed.co channel delivery to it. I want to use a flask application to receive web-hooks, derive a simple event description from them and then publish to the Redis channel for delivery over the Pushed.co service. I hope to have real-time notification for some services I use which have no alternative notification option.

**Comment by FGRibreau** [comment]
Oh I see @digmore, nice :+1:
